from __future__ import annotations

DEFAULT_OCR_VERSION = "PP-OCRv6"
DEFAULT_DEVICE = "cpu"
DEFAULT_RECONCILE_MODEL = "claude-sonnet-4-6"
DEFAULT_SUPERWHISPER_URL = "http://127.0.0.1:8787"

LANGUAGE_MAP = {
    "ara": "ar",
    "chi_sim": "ch",
    "chi_tra": "chinese_cht",
    "deu": "german",
    "eng": "en",
    "fa": "fa",
    "fas": "fa",
    "fra": "fr",
    "hin": "hi",
    "ita": "it",
    "jpn": "japan",
    "kor": "korean",
    "per": "fa",
    "por": "pt",
    "rus": "ru",
    "spa": "es",
    "tha": "th",
    "tur": "tr",
    "vie": "vi",
}

SUPPORTED_LANGUAGES = frozenset(
    {
        "af",
        "ar",
        "az",
        "bs",
        "ca",
        "ch",
        "chinese_cht",
        "cs",
        "cy",
        "da",
        "de",
        "en",
        "es",
        "et",
        "eu",
        "fa",
        "fi",
        "fr",
        "french",
        "ga",
        "german",
        "gl",
        "hr",
        "hu",
        "id",
        "is",
        "it",
        "japan",
        "ku",
        "la",
        "lb",
        "lt",
        "lv",
        "mi",
        "ms",
        "mt",
        "nl",
        "no",
        "oc",
        "pl",
        "pt",
        "qu",
        "rm",
        "ro",
        "rs_latin",
        "sk",
        "sl",
        "sq",
        "sv",
        "sw",
        "tl",
        "tr",
        "uz",
        "vi",
        *LANGUAGE_MAP,
    },
)
